version: "3.8"
services:
  pda_app:
    container_name: pda-app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - pda_db
    networks:
      - app_network

  pda_nginx:
    container_name: pda-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - pda_app
    environment:
      NGINX_FPM_HOST: pda_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  pda_db:
    container_name: pda-mysql
    platform: linux/x86_64
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

  pda_redis:
    container_name: pda-redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
